### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elidiot18** [YoPox/mdbg#2]
# To be done
- [ ] Figures and captions
- [ ] `{{{ … }}}` block (left bracket)
- [ ] `$$$ … $$$` block (non parsed latex)
- [ ] Text alignment (maybe with `!!:` at the begining/end of a line)
- [ ] Small capitals, highlighted and spaced style (see [soul package](http://texdoc.net/texmf-dist/doc/latex/soul/soul.pdf)) (maybe with syntax `/sc/text/sc/`, `/hi/text/hi/` and `/sp/text/sp/` respectively)
- [x] Footnotes (maybe with syntax `***{text}`)
- [x] Superscript and subscript text for example for "4th" (maybe with syntax `^{text}`)
- [x] Colored text (maybe with syntax `{color}(text)` where color can be "red" or **"#A82C10"** (_still to do_))

**Comment by elidiot18** [comment]
We can tick those little boxes once we have "done a todo"

**Comment by yopox** [comment]
We should add the following environment :

```latex
\[
\left \{
\begin{array}{l}
    |s| \geq 1 \\
    |rs| \leq n \leq n
\end{array}
\right.
\]
```

Which would translate to :

```md
{{{
    |s| \geq 1 \\
    |rs| \leq n \leq n
}}}
```

**Comment by yopox** [comment]
We should add the figure environment :

```latex
\begin{figure}[h]
  \centering
    \includegraphics[width=[[width]]\textwidth]{[[path]]}
  \caption{[[caption]]}
\end{figure}
```

We could use one of the following syntaxes :

```
![FIG width path][caption]
```

```
![FIG width path]
![CAP caption]
```

**Comment by yopox** [comment]
Add non parsed blocks delimited by `$$$`
